### PR TITLE
Homepage

### PR DESCRIPTION
**Pull request by adampaulukanis**
What we need here is the right font and size. I guess the colour is
correct?
I did not include webpage because it would point to itself ;-)
Text: '2018 Website design by' what colour it is? And background
colours.

### CODE REVIEW

**Comment by saqi** [comment]
What if you made the background colour (for "Website designed by ...") the same as the body so it looks like something separate, like in the original design 
        Maybank/Images/Cropped Design.png
Make the text color black and font which is thin so it's not obtrusive
something like coronet or Arial Narrow

Could there be more padding (maybe same amount as there is between mobile numbers & "Maybank Associates Limited") between "Maybank Associates Limited" and "A limited company ..." text?

**Comment by adampaulukanis** [comment]
Renamed the header of this PR.

**Comment by saqi** [comment]
> Renamed the header of this PR.

Footer was appropriate for this :P 

All good :+1: 

I think the shadowing on the main content doesn't look good, what do you think? I was thinking either leave it without shadow, use images mosaic style like in pinterest or use a single image like from [here](https://www.google.co.uk/search?q=mosaic+tiles+background&rlz=1C1LENP_enGB741GB745&tbm=isch&source=lnt&tbs=ic:specific,isc:brown&sa=X&ved=0ahUKEwjEur2e5qneAhVBalAKHeCtB90QpwUIIQ&biw=1366&bih=626&dpr=1).

**Review by saqi — APPROVED** [review]
All good, will just make a change to footer p (vat text) font size.

**Comment by adampaulukanis** [comment]
That's alright!

**Pull request merged**
