### PR TITLE
margin bottom on footer p

### PR DESCRIPTION
**Pull request by saqi**
Added 5px on p in footer for readability.

### CODE REVIEW

**Comment by saqi** [comment]
This PR is for the final touches the home page needs.
This is in response to some of Pierre's feedback as well as some small additions.

Starting from the top:

Make logo centered in relation to the left of the header and the text that is on the right (maybank associates & Architectural restorations)

What do you think about centering the text within the menu items?

Use this (original) image for 1st pic on carousel: https://www.hollandsfinishes.co.uk/wp-content/uploads/2013/02/Unique-Decorative-Finishes-980x556.jpg

Should we change the colour of the h1 &/or paragraph in the second section in main? black there looks a bit out of place; at least for the h1 it does.

I was thinking of having the testimonials text in something like monotype corsiva: https://www.wfonts.com/font/monotype-corsiva

Pierre also said to have:
    border-bottom-right-radius: 1em;
    border-bottom-left-radius: 1em;
on the .page as grid items have this style.

Finally I was thinking of getting an arrow on the bottom to point to "Website designed by ... " text
See this video: https://www.youtube.com/watch?v=QY7Rj8aZcZk
tutorial for arrow starts at 3:45

If you have any improvements too feel free to propose them here :)
Edit: if you think bottom padding should be more feel free to increase, I think 7/8 px might be better

**Comment by saqi** [comment]
Overall I think it's an improvement in everything :)

Few last changes (& maybe big ones):

The font size and margin top of a limited company text is quite large on mobile version

The left part of the arrow that points to designed by text has a gradient? Was that intentional? I think plain would be better

The container that holds website designed by text also is quite large whereas it's supposed to be minimal to attract last attention from the website

I saw the website at work computer yesterday which was on a wide-screen monitor and it was kind of broken i.e the font size for everything was larger hence didn't fit. I'll try to get screenshots if I get to work at same computer, should we try fix it? I think it'll be difficult to fix as I tried looking at it on chrome's different views using the developer tools but it looked fine on there

Last but not least the text in the carousel doesn't fit on mobile version, I think it could be buggy too. If you have the same experience or can't fix it I think hiding it on mobile is ok

Thank you :) 

We'll propose the designs once this is done :D

**Comment by saqi** [comment]
Note the text size and how it doesn't fit in the grid

image

The arrow also doesn't come properly here

image

**Comment by adampaulukanis** [comment]
> The font size and margin top of a limited company text is quite large on mobile version

Sorry I am not sure what you mean by that. I checked it on my mobile and it looks OK.

I will take care of JavaScript Tomorrow. Good night ;-)

**Comment by adampaulukanis** [comment]
Is it better now? How is your weekend? :blush:

**Comment by saqi** [comment]
Almost perfect (sorry :P )

The text within the grid has changed I'll put pic of original and new to show difference:

Master branch: 
image

PR: 
image

Edit: As you can see the master branch one fills the grid cell up so I think it looks better, also padding top on the h4 which vertically centers it on the pre-hover display. (I'll do that now too).

Apart from that I think giving each testimonial a top left & top right border radius would make it look ok. What do you think? I'll try change it now if I can.

Weekend is good, haven't seen you around, hope everything is going well for you.

**Comment by saqi** [comment]
"Proposed changes have been commented, please comment your styles and uncomment mine to see proposed changes)"

My aim is to make it look like this:

image

**Comment by adampaulukanis** [comment]
> "Proposed changes have been commented, please comment your styles and uncomment mine to see proposed changes)"
> 
> My aim is to make it look like this:
> 
> image

You are right! It looks better ;-)

Text within the grids changed because I was not sure how to solve the problem. I changed the font family and size and it fit I hope.

**Comment by saqi** [comment]
Hello,

Width of testimonial ul is 100% not 98% as stated in commit.
According to chrome developer tools it works fine on all devices, please check on your device if you are able to do so.

If you are happy with changes and don't want to do the text for the widescreen approve and merge so I can send to pierre :)

**Comment by adampaulukanis** [comment]
ok

**Review by adampaulukanis — COMMENTED** [review]
nice ;-)

**Review by adampaulukanis — APPROVED** [review]

**Pull request merged**
