### PR TITLE
Testimonials

### PR DESCRIPTION
**Pull request by adampaulukanis**
I know, it is not good but something to start with ;)

### CODE REVIEW

**Comment by saqi** [comment]
Love the concept, thought the colours didn't match the theme of the website so commited changes, don't git pull if you don't like them ;)

Was also thinking of changing the order of the elements and removing the address as well as adding the company; see pics below.

image

image

Can compare which one's look better.

The code for the changes I made (although the quotes are not coming for some reason, I'll include it below):
```
<li>
            <div class="content">
              <img src="./Images/person5.png" alt="Person 2">
              <p>“Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec sollicitudin ante leo, ac lacinia lectus.”</p>                
                <h3>Larry D. Ogawa</h3>								
                <h5>Company</h5>
            </div>
</li>
```

Double quotes  | “ ” | 
'&ldquo;' '&rdquo;'

Also I think the images would work better if they were of real people instead of the current art images, what do you think?

**Comment by adampaulukanis** [comment]
> Love the concept, thought the colours didn't match the theme of the website so commited changes, don't git pull if you don't like them ;)

OK

> 
> Was also thinking of changing the order of the elements and removing the address as well as adding the company; see pics below.

<snip>

That's nice but I was thinking that company's clients are (or will be) normal people or not? Other companies? It can be changed easily and the real photos would be better indeed but where we are going get them from? ;-) 

Address or company? Can be changed.

And last thing: I added **"** but we can use CSS:
`p::after, p::before { content: "\""; }`.

**Comment by saqi** [comment]
Yh, I showed this to Raf and he agreed, I think take the address out as well.
Try experimenting the "Quote" text with different colours like gold or the brown that is used, if it doesn't look good keep it as black.

What pics are used for the people? If they're normal sized images we can use stock photos otherwise we can just leave it and concentrate on finishing this up.

Lastly what do you think about the Testimonials title text above the testimonials section?

I thought we can make it the brown colour and center it or remove it altogether unless you have a better idea?

**Comment by adampaulukanis** [comment]
can do ;)

**Review by saqi — APPROVED** [review]
Great stuff, I don't think it's worth to make it perfect as it's still a proposal and would obviously look better with professional photos.

Good choice in colour :+1:

**Pull request merged**
