### PR TITLE
Header: What do you think?

### PR DESCRIPTION
**Pull request by adampaulukanis**
We can try using Google Fonts and find a closest match possible or leave
it for now.

### CODE REVIEW

**Comment by saqi** [comment]
Much better, if you can make the menu tabs start from the text (after the logo) and spread them across to the end (it can be easily done in css grid if it'll be a pain in flexbox) I think it would be enough :)

**Comment by adampaulukanis** [comment]
screen shot 2018-10-29 at 19 49 42
And I got rid of that black line. Does it look better now? ;-)

**Comment by saqi** [comment]
Great, is it possible to start the menu tab where the text above it starts?

It's better without the black line too :+1

**Comment by adampaulukanis** [comment]
Sorry. I do not get it.

Can you draw it in a graphics app and include it here or send it to me via
whatever?

**Comment by adampaulukanis** [comment]
Hehe. Now, when I saw the picture I posted I got what you mean! I will do it.-)

**Comment by adam17** [comment]
If you are happy please close this PR.

**Comment by saqi** [comment]
BTW if you prefer coding these minor changes yourself let me know & I'll stay out of your way :) I only do them once you have done the main tasks and instead of merging my perfectionist self wants a pixel change and I didn't want to trouble you for that especially if it can be done quickly and we can move forward too!

**Comment by adampaulukanis** [comment]
You are alright. I appreciate your effort. I cannot check it now because my phone's display is too narrow. I will have a look once I get home after work.
And I need to remember about doing `git pull`. Last time I forgot 🎃

**Comment by adampaulukanis** [comment]
I guess we can close this PR. The name is confusing: *header*.

**Comment by saqi** [comment]
> I guess we can close this PR. The name is confusing: _header_.

Yh, please approve & merge first so I can close it. Thanks!

**Review by saqi — APPROVED** [review]
Approved by both

**Pull request merged**
